services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nutrition_user
      POSTGRES_PASSWORD: nutrition_pass
      POSTGRES_DB: nutrition_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: NutritionAdvisor.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Database=nutrition_db;Username=nutrition_user;Password=nutrition_pass
      Jwt__Key: CHANGE_ME_TO_A_SECURE_KEY_WITH_AT_LEAST_32_CHARS
      Jwt__Issuer: NutritionAdvisor
      Jwt__Audience: NutritionAdvisorUsers
      PythonAI__BaseUrl: http://ai_service:8000
      Stripe__SecretKey: sk_test_PUNE_CHEIA_AICI_IN_LOCAL
      Stripe__WebhookSecret: sk_test_PUNE_CHEIA_AICI_IN_LOCAL
      Stripe__Domain: http://localhost:5210
    ports:
      - "5066:8080"
    volumes:
      - ./NutritionAdvisor.API/wwwroot/UploadedFiles:/app/wwwroot/UploadedFiles
    depends_on:
      - postgres
      - ai_service

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "5210:80"
    
  ai_service:
    build:
      context: NutritionAdvisor.AI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

volumes:
  postgres_data:
