using System.Net.Http.Json;
using System.Text.Json.Serialization;
using NutritionAdvisor.Application.AI;
using NutritionAdvisor.Application.Interfaces;
using NutritionAdvisor.Infrastructure.Options;
using Microsoft.Extensions.Options;

namespace NutritionAdvisor.Infrastructure.Services;

public sealed class PythonAiService : IPythonAiService
{
    private readonly HttpClient _httpClient;

    public PythonAiService(HttpClient httpClient, IOptions<PythonAiOptions> options)
    {
        _httpClient = httpClient;

        var baseUrl = options.Value.BaseUrl;
        if (httpClient.BaseAddress == null && !string.IsNullOrWhiteSpace(baseUrl))
        {
            _httpClient.BaseAddress = new Uri(baseUrl, UriKind.Absolute);
        }
    }

    public async Task<IReadOnlyList<AiRecommendationItemDto>> RecommendRecipesAsync(AiContextDto context, int limit, CancellationToken cancellationToken)
    {
        var response = await _httpClient.PostAsJsonAsync("/recommend", new PythonRecommendationRequest(context, limit), cancellationToken);
        response.EnsureSuccessStatusCode();

        var payload = await response.Content.ReadFromJsonAsync<PythonRecommendationResponse>(cancellationToken: cancellationToken);
        return payload?.Recommendations ?? [];
    }

    public async Task<AiMealPlanResponseDto> GenerateMealPlanAsync(AiContextDto context, int days, CancellationToken cancellationToken)
    {
        var response = await _httpClient.PostAsJsonAsync("/meal-plan", new PythonMealPlanRequest(context, days), cancellationToken);
        response.EnsureSuccessStatusCode();

        var payload = await response.Content.ReadFromJsonAsync<PythonMealPlanResponse>(cancellationToken: cancellationToken);
        return new AiMealPlanResponseDto(
            context.UserId,
            "Premium",
            payload?.Summary ?? "Meal plan generated by Python AI.",
            payload?.Days ?? []);
    }

    public async Task<AiCoachResponseDto> AskCoachAsync(AiContextDto context, string message, string? extraContext, CancellationToken cancellationToken)
    {
        var response = await _httpClient.PostAsJsonAsync("/coach", new PythonCoachRequest(context, message, extraContext), cancellationToken);
        response.EnsureSuccessStatusCode();

        var payload = await response.Content.ReadFromJsonAsync<PythonCoachResponse>(cancellationToken: cancellationToken);
        return new AiCoachResponseDto(
            context.UserId,
            "Premium",
            payload?.Answer ?? "AI coach response unavailable.",
            payload?.Tips ?? []);
    }

    private sealed record PythonRecommendationRequest(
        [property: JsonPropertyName("user_id")] Guid UserId,
        [property: JsonPropertyName("objective")] string? Objective,
        [property: JsonPropertyName("allergies")] IReadOnlyList<string> Allergies,
        [property: JsonPropertyName("disliked_ingredients")] IReadOnlyList<string> DislikedIngredients,
        [property: JsonPropertyName("limit")] int Limit)
    {
        public PythonRecommendationRequest(AiContextDto context, int limit)
            : this(context.UserId, context.Objective, context.Allergies, context.DislikedIngredients, limit)
        {
        }
    }

    private sealed record PythonRecommendationResponse(
        [property: JsonPropertyName("user_id")] Guid UserId,
        [property: JsonPropertyName("recommendations")] IReadOnlyList<AiRecommendationItemDto> Recommendations);

    private sealed record PythonMealPlanRequest(
        [property: JsonPropertyName("user_id")] Guid UserId,
        [property: JsonPropertyName("objective")] string? Objective,
        [property: JsonPropertyName("days")] int Days,
        [property: JsonPropertyName("allergies")] IReadOnlyList<string> Allergies,
        [property: JsonPropertyName("disliked_ingredients")] IReadOnlyList<string> DislikedIngredients)
    {
        public PythonMealPlanRequest(AiContextDto context, int days)
            : this(context.UserId, context.Objective, days, context.Allergies, context.DislikedIngredients)
        {
        }
    }

    private sealed record PythonMealPlanResponse(
        [property: JsonPropertyName("user_id")] Guid UserId,
        [property: JsonPropertyName("summary")] string Summary,
        [property: JsonPropertyName("days")] IReadOnlyList<AiMealPlanDayDto> Days);

    private sealed record PythonCoachRequest(
        [property: JsonPropertyName("user_id")] Guid UserId,
        [property: JsonPropertyName("objective")] string? Objective,
        [property: JsonPropertyName("message")] string Message,
        [property: JsonPropertyName("context")] string? Context,
        [property: JsonPropertyName("allergies")] IReadOnlyList<string> Allergies,
        [property: JsonPropertyName("disliked_ingredients")] IReadOnlyList<string> DislikedIngredients)
    {
        public PythonCoachRequest(AiContextDto context, string message, string? extraContext)
            : this(context.UserId, context.Objective, message, extraContext, context.Allergies, context.DislikedIngredients)
        {
        }
    }

    private sealed record PythonCoachResponse(
        [property: JsonPropertyName("user_id")] Guid UserId,
        [property: JsonPropertyName("answer")] string Answer,
        [property: JsonPropertyName("tips")] IReadOnlyList<string> Tips);
}
